version: '3.4'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: app
    # restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - './:/var/www/html'
    restart: always
    networks:
      - website

  nginx:
    image: 'nginx:alpine'
    # container_name: nginx
    restart: always
    #tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './:/var/www/html'
      - './nginx/conf.d/:/etc/nginx/conf.d/'
      - './nginx/ssl/:/etc/nginx/ssl/'
    networks:
      - website

  db:
    image: 'mysql:5.7'
    # container_name: db
    restart: always
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: forge
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - 'db_data:/var/lib/mysql/'
    networks:
      - website

    # node:
    #   image: 'node:10-alpine'
    #   # container_name: node
    #   working_dir: /usr/src/app
    #   volumes:
    #     - './:/usr/src/app'
    #     - './:/'
    #   entrypoint:
    #     - /docker_node_run.sh
    #   depends_on:
    #     - app

networks:
  website:
    driver: bridge

volumes:
  db_data:
    driver: local
